name 'wirbelsturm-build'
version '1.0.2'
source 'https://github.com/miguno/puppet-wirbelsturm_build.git'
author 'Michael G. Noll'
license 'Apache License, Version 2.0'
summary 'Module for managing and configuring Wirbelsturm build servers'
description 'Module for managing and configuring Wirbelsturm build servers'
project_page 'https://github.com/miguno/puppet-wirbelsturm_build'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
